[package]
name = "repo_analyzer"
version = "0.1.0"
authors = ["Luc Tielen <luc.tielen@kabisa.nl>"]

[dependencies]
rocket = "0.3.12"
rocket_codegen = "0.3.12"
rocket_contrib = { version = "0.3.12", default-features = false, features = ["tera_templates"] }
tera = "0.11.7"
git2 = "0.7.1"
